service: lossibot

provider:
  name: aws
  runtime: nodejs16.x
  stage: prod
  region: eu-north-1

functions:
  webhook:
    handler: handler.webhook
    environment:
      LOSSI_BOT_TOKEN: ${ssm:/lossibot/prod/token}
    events:
      - http:
          path: webhook
          method: post
          cors: true
  set-webhook:
    handler: handler.setWebhook
    environment:
      LOSSI_BOT_TOKEN: ${ssm:/lossibot/prod/token}
    events:
      - http:
          path: setWebhook
          method: post
          cors: true
