name: deploy
on:
  push:
    branches:
      - "master"
  pull_request:
    
jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          
      - name: Install AWS SAM CLI
        run: |
          curl -fsSL https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o aws-sam-cli.zip
          unzip aws-sam-cli.zip -d sam-installation
          sudo ./sam-installation/install --update
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Install dependencies
        run: yarn install
        
      - name: Build TypeScript
        run: yarn build
        
      - name: Build SAM template
        run: sam build
        
      - name: Deploy SAM template
        run: sam deploy --stack-name lossibot --resolve-s3 --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset
        
      - name: Set webhook
        run: |
          API_URL=$(aws cloudformation describe-stacks --stack-name lossibot --query 'Stacks[0].Outputs[?OutputKey==`WebhookEndpoint`].OutputValue' --output text)
          curl -X POST $API_URL/setWebhook
