name: deploy
on:
  push:
    branches:
      - "master"
jobs:
  deploy-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Serverless
        run: npm install -g serverless
      - name: Add AWS authentication for Serverless
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Install NPM dependencies
        run: npm install
      - name: Deploy Lambda functions
        run: sls deploy
      - name: Set webhook
        run: curl -X POST https://${{ secrets.AWS_API_ID }}.execute-api.eu-north-1.amazonaws.com/prod/setWebhook
